name: HomeLibrary
options:
  bundleIdPrefix: com.maazmukhtar
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    INFOPLIST_KEY_CFBundleDisplayName: "Home Library"
    INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.books"
    ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "AccentColor"
    ENABLE_PREVIEWS: "YES"
    DEVELOPMENT_TEAM: ""

targets:
  HomeLibrary:
    type: application
    platform: iOS
    sources:
      - path: HomeLibrary
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.maazmukhtar.HomeLibrary
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_NSCameraUsageDescription: "Scan book barcodes and capture cover photos"
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "Select book cover images from your library"
        SWIFT_EMIT_LOC_STRINGS: YES
        GENERATE_INFOPLIST_FILE: YES

  HomeLibraryTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: HomeLibraryTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: HomeLibrary
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.maazmukhtar.HomeLibraryTests
        GENERATE_INFOPLIST_FILE: YES

  HomeLibraryUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: HomeLibraryUITests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: HomeLibrary
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.maazmukhtar.HomeLibraryUITests
        GENERATE_INFOPLIST_FILE: YES

schemes:
  HomeLibrary:
    build:
      targets:
        HomeLibrary: all
        HomeLibraryTests: [test]
        HomeLibraryUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - HomeLibraryTests
        - HomeLibraryUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
